### ISSUE TITLE
tksheet version issue

### ISSUE THREAD

**Issue by SMVSKN** [VarunS2002/Python-NSE-Option-Chain-Analyzer#64]
Does not work with latest version of tksheet-7.0. Had to revert back to 6.3.5.
With new version getting exception below:

UserWarning: There have been many changes from tksheet version 6.x.x to version 7.x.x. Please see the changelog for more information.
  WARNING(
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/tkinter/__init__.py", line 1895, in __call__
    return self.func(*args)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 817, in callit
    func(*args)
  File "./NSE_OptionChain_analyser.py", line 1536, in main
    self.set_values()
  File "./NSE_OptionChain_analyser.py", line 1282, in set_values
    self.sheet.insert_row(values=output_values, add_columns=True)
TypeError: insert_row() got an unexpected keyword argument 'values'

**Comment by SMVSKN** [comment]
One option could be just to fix the tksheet version in the requirements file.

**Comment by VarunS2002** [comment]
> One option could be just to fix the tksheet version in the requirements file.

Yes that is the plan. Thanks for reporting this issue.

**Comment by Jassi9** [comment]
Thanks. It worked after downgraded the version to 6.3.5

**Comment by VarunS2002** [comment]
Fixed in the [latest version](https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer/releases/5.6).
